import type { Exhibit } from "../types.js";

function dragonTurns(iterations: number): string {
  let seq = "R";
  for (let i = 0; i < iterations; i++) {
    seq =
      seq +
      "R" +
      seq
        .split("")
        .reverse()
        .map((c) => (c === "L" ? "R" : "L"))
        .join("");
  }
  return seq;
}

function drawDragon(
  ctx: CanvasRenderingContext2D,
  cx: number,
  cy: number,
  length: number,
  turns: string,
  angleDeg: number,
): void {
  let x = cx;
  let y = cy;
  let angle = (-angleDeg * Math.PI) / 180;
  const step = length / (turns.length + 1);

  ctx.beginPath();
  ctx.moveTo(x, y);

  for (const t of turns) {
    x += Math.cos(angle) * step;
    y += Math.sin(angle) * step;
    ctx.lineTo(x, y);
    angle += t === "R" ? -Math.PI / 2 : Math.PI / 2;
  }

  ctx.stroke();
}

export const dragonCurve: Exhibit = {
  id: "dragon-curve",
  path: "/dragon-curve",
  title: "Dragon Curve",
  category: "Fractals",
  summary: "A space-filling fractal built by folding a strip at right angles.",
  maths:
    "The Heighway dragon is generated by the L-system F → F+G, G → F−G with ±90° turns. " +
    "Equivalently, iterate: S → S+R+S̃− where S̃ reverses S and swaps L↔R. " +
    "After n folds the curve has 2ⁿ segments yet never crosses itself.",
  params: [
    { id: "iterations", label: "Iterations", type: "number", min: 1, max: 14, step: 1 },
    { id: "angle", label: "Initial angle", type: "number", min: 0, max: 360, step: 5 },
    { id: "lineWidth", label: "Line width", type: "number", min: 0.5, max: 4, step: 0.5 },
    {
      id: "colorMode",
      label: "Color",
      type: "select",
      options: [
        { value: "gradient", label: "Gradient" },
        { value: "gold", label: "Gold" },
        { value: "cyan", label: "Cyan" },
      ],
    },
  ],
  defaults: {
    iterations: 10,
    angle: 0,
    lineWidth: 1.5,
    colorMode: "gradient",
  },
  width: 960,
  height: 720,
  exportFilename: "dragon-curve.png",
  draw(ctx, width, height, values) {
    const iterations = values.iterations as number;
    const angle = values.angle as number;
    const lineWidth = values.lineWidth as number;
    const colorMode = values.colorMode as string;

    ctx.fillStyle = "#0a0f1a";
    ctx.fillRect(0, 0, width, height);

    const turns = dragonTurns(iterations);
    const size = Math.min(width, height) * 0.75;

    if (colorMode === "gradient") {
      const grad = ctx.createLinearGradient(0, 0, width, height);
      grad.addColorStop(0, "#6366f1");
      grad.addColorStop(0.5, "#a855f7");
      grad.addColorStop(1, "#ec4899");
      ctx.strokeStyle = grad;
    } else if (colorMode === "gold") {
      ctx.strokeStyle = "#fbbf24";
    } else {
      ctx.strokeStyle = "#22d3ee";
    }

    ctx.lineWidth = lineWidth;
    ctx.lineCap = "round";
    ctx.lineJoin = "round";

    drawDragon(ctx, width * 0.32, height * 0.55, size, turns, angle);
  },
};
