export {
  prepareCanvas,
  DEFAULT_CANVAS_WIDTH,
  DEFAULT_CANVAS_HEIGHT,
  DEFAULT_CANVAS_ASPECT,
  RENDER_CANVAS_WIDTH as FLAGSHIP_CANVAS_WIDTH,
  RENDER_CANVAS_HEIGHT as FLAGSHIP_CANVAS_HEIGHT,
  RENDER_CANVAS_ASPECT as FLAGSHIP_CANVAS_ASPECT,
  RENDER_SIM_GRID as FLAGSHIP_SIM_GRID,
  RENDER_MAX_DPR as FLAGSHIP_MAX_DPR,
  RENDER_IMMERSIVE_MAX_DPR as FLAGSHIP_IMMERSIVE_MAX_DPR,
} from "@platform/render";
export type { PrepareCanvasOptions } from "@platform/render";
