import type { FileAreaGroup, RunArtifact, RunCompletionSummary } from "../api/types.js";

export interface ScreenshotContext {
  /** Human page/section name this screenshot belongs to. */
  pageName: string;
  /** Why this screenshot was captured. */
  purpose: string;
  /** What a reviewer should expect to see change on this page. */
  expectedUserChange: string;
  /** Files most likely responsible for what's shown, best-effort matched. */
  filesResponsible: string[];
  /** What stage/action this capture happened after. */
  capturedAfter: string;
  /** Short one-line caption for the walkthrough step. */
  caption: string;
}

export interface BuildScreenshotContextArgs {
  artifact: RunArtifact;
  completionSummary: RunCompletionSummary | null;
  /** Position of this screenshot within the ordered walkthrough (0-based). */
  index: number;
  /** Total number of screenshots in the walkthrough. */
  total: number;
}

/**
 * Derives human-readable storytelling context for a single screenshot artifact,
 * using whatever completion-summary metadata is available. Always returns
 * sensible, specific-sounding fallbacks — never "unknown".
 */
export function buildScreenshotContext({
  artifact,
  completionSummary,
  index,
  total,
}: BuildScreenshotContextArgs): ScreenshotContext {
  const pageName = derivePageName(artifact, index, total);
  const capturedAfter = deriveCapturedAfter(artifact);
  const filesResponsible = deriveFilesResponsible(pageName, completionSummary);
  const expectedUserChange = deriveExpectedUserChange(completionSummary, index, pageName);
  const purpose = derivePurpose(artifact, pageName, completionSummary);
  const caption = artifact.caption?.trim() || `${pageName} — ${purpose}`;

  return { pageName, purpose, expectedUserChange, filesResponsible, capturedAfter, caption };
}

function derivePageName(artifact: RunArtifact, index: number, total: number): string {
  if (artifact.pageLabel?.trim()) return artifact.pageLabel.trim();
  if (artifact.pageKey?.trim()) return titleCase(artifact.pageKey.trim());
  const base = artifact.filename.replace(/\.[a-z0-9]+$/i, "");
  const cleaned = base.replace(/[-_]*(before|after|diff)$/i, "").trim();
  const titled = titleCase(cleaned);
  if (titled) return titled;
  return total > 1 ? `Screenshot ${index + 1} of ${total}` : "Screenshot";
}

function derivePurpose(
  artifact: RunArtifact,
  pageName: string,
  completionSummary: RunCompletionSummary | null,
): string {
  const matchedChange = findMatchingChange(pageName, completionSummary?.userVisibleChanges);
  if (matchedChange) return matchedChange;

  if (artifact.kind === "image_diff") {
    return `Visual diff highlighting exactly what changed on ${pageName}.`;
  }
  if (artifact.phase === "before") {
    return `Baseline capture of ${pageName} before this run's changes were applied.`;
  }
  if (artifact.phase === "after") {
    return `Confirms how ${pageName} looks after this run's changes were applied.`;
  }
  return `Visual validation capture of ${pageName} for this run.`;
}

function deriveExpectedUserChange(
  completionSummary: RunCompletionSummary | null,
  index: number,
  pageName: string,
): string {
  const changes = (completionSummary?.userVisibleChanges ?? []).filter(
    (c) => c && c.trim().length > 0,
  );
  if (changes.length > 0) {
    return changes[index % changes.length]!.trim();
  }
  const overviewFirstLine = firstNonEmptyLine(completionSummary?.overview);
  if (overviewFirstLine) return overviewFirstLine;
  if (completionSummary?.executiveSummary?.trim()) {
    return completionSummary.executiveSummary.trim();
  }
  return `Review ${pageName} for correct rendering and behavior after this run.`;
}

function deriveFilesResponsible(
  pageName: string,
  completionSummary: RunCompletionSummary | null,
): string[] {
  const groups = completionSummary?.filesModified ?? [];
  if (groups.length === 0) return ["Not recorded for this run"];

  const lowerPage = pageName.toLowerCase();
  const matched = groups.filter((g) => areaMatchesPage(g.area, lowerPage));
  const chosen = matched.length > 0 ? matched : groups;
  const files = dedupe(chosen.flatMap((g: FileAreaGroup) => g.files));
  return files.length > 0 ? files : ["Not recorded for this run"];
}

function deriveCapturedAfter(artifact: RunArtifact): string {
  if (artifact.phase === "before") {
    return "Captured before this run's changes were applied (baseline).";
  }
  if (artifact.phase === "after") {
    return "Captured after this run's changes were applied.";
  }
  if (artifact.kind === "image_diff") {
    return "Generated by comparing the before and after captures.";
  }
  return "Captured during this run's artifact collection.";
}

function findMatchingChange(pageName: string, changes: string[] | undefined): string | null {
  if (!changes?.length) return null;
  const lowerPage = pageName.toLowerCase();
  const pageWords = lowerPage.split(/\s+/).filter((w) => w.length > 2);
  for (const change of changes) {
    const lowerChange = change.toLowerCase();
    if (lowerChange.includes(lowerPage)) return change.trim();
    if (pageWords.some((w) => lowerChange.includes(w))) return change.trim();
  }
  return null;
}

function areaMatchesPage(area: string, lowerPage: string): boolean {
  const lowerArea = area.toLowerCase();
  if (lowerArea.includes(lowerPage) || lowerPage.includes(lowerArea)) return true;
  const areaWords = lowerArea.split(/\s+/).filter((w) => w.length > 2);
  const pageWords = lowerPage.split(/\s+/).filter((w) => w.length > 2);
  return areaWords.some((w) => pageWords.includes(w));
}

function firstNonEmptyLine(text: string | null | undefined): string | null {
  if (!text) return null;
  const line = text
    .split(/\r?\n/)
    .map((l) => l.trim())
    .find((l) => l.length > 0);
  return line ?? null;
}

function titleCase(text: string): string {
  return text
    .replace(/[-_]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ")
    .trim();
}

function dedupe(items: string[]): string[] {
  return [...new Set(items.map((i) => i.trim()).filter(Boolean))];
}
